---
title: "Try Rcpp"
author: "Pratheepa Jeganathan"
date: "4/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Rcpp)

```

```{r}
cppFunction('int add(int x, int y, int z) {
  int sum = x + y + z;
  return sum;
}')

add(1,2,3)
```

```{r}
one <- function() 1L
```

```{r}
fn = 'int one() {
  return 1;
}'
```

```{r}
cppFunction(fn)
one()
```

```{r}
# signR <- function(x) {
#   if (x > 0) {
#     1
#   } else if (x == 0) {
#     0
#   } else {
#     -1
#   }
# }


cppFunction('int signR(int x){
  if (x > 0) {
    return 1;
  } else if (x == 0){
    return 0;
  } else{
    return -1;
  }
}')
signR(10)
```
```{r}
sumR = function(x){
  total = 0
  for(i in seq_along(x)){
    total = total + x[i]
  }
  total
}
```

```{r}
cppFunction('double sumC(NumericVector x){
  int n = x.size();
  double total = 0;
  for(int i = 0; i < n; ++i){
  total += x[i];
  }
  return total;
  }')
```

```{r}
library(microbenchmark)
x = runif(1e3)
microbenchmark(sum(x), sumR(x), sumC(x))
```

